const ADMIN_CREDENTIAL = {
  email: 'admin@smarthire.com',
  password: 'admin123',
  role: 'admin',
};

const DEMO_STUDENTS = [
  { email: 'arjun.sharma@student.com', password: 'demo123', full_name: 'Arjun Sharma', phone: '9876500001', department: 'Computer Science', year_of_study: 3, cgpa: 8.9, coding_score: 82, bio: 'Full-stack focused student with strong problem solving skills.', linkedin_url: 'https://linkedin.com/in/arjun-sharma', github_url: 'https://github.com/arjunsharma', resume_url: null, skills: [1, 6, 7, 10, 34] },
  { email: 'priya.nair@student.com', password: 'demo123', full_name: 'Priya Nair', phone: '9876500002', department: 'Information Technology', year_of_study: 4, cgpa: 9.2, coding_score: 91, bio: 'Frontend and analytics enthusiast with internship experience.', linkedin_url: 'https://linkedin.com/in/priya-nair', github_url: 'https://github.com/priyanair', resume_url: null, skills: [2, 9, 24, 8, 34] },
  { email: 'rahul.verma@student.com', password: 'demo123', full_name: 'Rahul Verma', phone: '9876500003', department: 'Computer Science', year_of_study: 3, cgpa: 7.5, coding_score: 70, bio: 'Backend-oriented student learning distributed systems.', linkedin_url: 'https://linkedin.com/in/rahul-verma', github_url: 'https://github.com/rahulverma', resume_url: null, skills: [3, 27, 8, 10, 34] },
  { email: 'sneha.patel@student.com', password: 'demo123', full_name: 'Sneha Patel', phone: '9876500004', department: 'Electronics', year_of_study: 4, cgpa: 8.1, coding_score: 65, bio: 'Interested in embedded systems and software integration.', linkedin_url: 'https://linkedin.com/in/sneha-patel', github_url: 'https://github.com/snehapatel', resume_url: null, skills: [1, 30, 6, 38, 37] },
  { email: 'karthik.r@student.com', password: 'demo123', full_name: 'Karthik R', phone: '9876500005', department: 'Computer Science', year_of_study: 2, cgpa: 8.7, coding_score: 88, bio: 'Early-career developer with strong cloud fundamentals.', linkedin_url: 'https://linkedin.com/in/karthik-r', github_url: 'https://github.com/karthikr', resume_url: null, skills: [2, 9, 24, 42, 10] },
  { email: 'divya.menon@student.com', password: 'demo123', full_name: 'Divya Menon', phone: '9876500006', department: 'Information Technology', year_of_study: 4, cgpa: 9.0, coding_score: 78, bio: 'UI engineer with interest in design systems and APIs.', linkedin_url: 'https://linkedin.com/in/divya-menon', github_url: 'https://github.com/divyamenon', resume_url: null, skills: [1, 6, 30, 39, 36] },
  { email: 'vikram.singh@student.com', password: 'demo123', full_name: 'Vikram Singh', phone: '9876500007', department: 'Computer Science', year_of_study: 3, cgpa: 7.8, coding_score: 72, bio: 'Systems programming learner focused on C and C++.', linkedin_url: 'https://linkedin.com/in/vikram-singh', github_url: 'https://github.com/vikramsingh', resume_url: null, skills: [4, 5, 10, 42, 35] },
  { email: 'ananya.kumar@student.com', password: 'demo123', full_name: 'Ananya Kumar', phone: '9876500008', department: 'Data Science', year_of_study: 4, cgpa: 9.4, coding_score: 95, bio: 'Top-performing data science student with ML project work.', linkedin_url: 'https://linkedin.com/in/ananya-kumar', github_url: 'https://github.com/ananyakumar', resume_url: null, skills: [2, 9, 24, 8, 34] },
  { email: 'rohan.das@student.com', password: 'demo123', full_name: 'Rohan Das', phone: '9876500009', department: 'Computer Science', year_of_study: 3, cgpa: 7.2, coding_score: 60, bio: 'Generalist student exploring backend and DevOps tooling.', linkedin_url: 'https://linkedin.com/in/rohan-das', github_url: 'https://github.com/rohandas', resume_url: null, skills: [1, 7, 19, 22, 39] },
  { email: 'pooja.iyer@student.com', password: 'demo123', full_name: 'Pooja Iyer', phone: '9876500010', department: 'Information Technology', year_of_study: 4, cgpa: 8.5, coding_score: 80, bio: 'Interested in Java backend and cloud deployment.', linkedin_url: 'https://linkedin.com/in/pooja-iyer', github_url: 'https://github.com/poojaiyer', resume_url: null, skills: [3, 27, 8, 21, 34] },
  { email: 'aditya.joshi@student.com', password: 'demo123', full_name: 'Aditya Joshi', phone: '9876500011', department: 'Computer Science', year_of_study: 2, cgpa: 8.3, coding_score: 76, bio: 'Second-year student building React and Node projects.', linkedin_url: 'https://linkedin.com/in/aditya-joshi', github_url: 'https://github.com/adityajoshi', resume_url: null, skills: [1, 6, 7, 30, 37] },
  { email: 'meera.pillai@student.com', password: 'demo123', full_name: 'Meera Pillai', phone: '9876500012', department: 'AI & ML', year_of_study: 4, cgpa: 9.1, coding_score: 93, bio: 'Machine learning specialist with deployment experience.', linkedin_url: 'https://linkedin.com/in/meera-pillai', github_url: 'https://github.com/meerapillai', resume_url: null, skills: [2, 9, 24, 42, 10] },
  { email: 'suresh.babu@student.com', password: 'demo123', full_name: 'Suresh Babu', phone: '9876500013', department: 'Computer Science', year_of_study: 3, cgpa: 7.0, coding_score: 55, bio: 'Strong fundamentals in Java and databases.', linkedin_url: 'https://linkedin.com/in/suresh-babu', github_url: 'https://github.com/sureshbabu', resume_url: null, skills: [3, 8, 10, 34, 35] },
  { email: 'lakshmi.n@student.com', password: 'demo123', full_name: 'Lakshmi N', phone: '9876500014', department: 'Information Technology', year_of_study: 4, cgpa: 8.8, coding_score: 85, bio: 'Product-minded developer focused on frontend UX.', linkedin_url: 'https://linkedin.com/in/lakshmi-n', github_url: 'https://github.com/lakshmin', resume_url: null, skills: [1, 6, 29, 38, 36] },
  { email: 'nikhil.gupta@student.com', password: 'demo123', full_name: 'Nikhil Gupta', phone: '9876500015', department: 'Computer Science', year_of_study: 3, cgpa: 8.0, coding_score: 74, bio: 'Algorithms and system design learner preparing for SDE roles.', linkedin_url: 'https://linkedin.com/in/nikhil-gupta', github_url: 'https://github.com/nikhilgupta', resume_url: null, skills: [31, 32, 33, 35, 34] },
  { email: 'kavya.reddy@student.com', password: 'demo123', full_name: 'Kavya Reddy', phone: '9876500016', department: 'Data Science', year_of_study: 4, cgpa: 9.3, coding_score: 90, bio: 'Data engineering and analytics focused final-year student.', linkedin_url: 'https://linkedin.com/in/kavya-reddy', github_url: 'https://github.com/kavyareddy', resume_url: null, skills: [2, 9, 24, 8, 40] },
  { email: 'amit.chauhan@student.com', password: 'demo123', full_name: 'Amit Chauhan', phone: '9876500017', department: 'Computer Science', year_of_study: 2, cgpa: 7.6, coding_score: 68, bio: 'Growing experience in backend APIs and deployment.', linkedin_url: 'https://linkedin.com/in/amit-chauhan', github_url: 'https://github.com/amitchauhan', resume_url: null, skills: [1, 7, 19, 39, 34] },
  { email: 'shreya.bose@student.com', password: 'demo123', full_name: 'Shreya Bose', phone: '9876500018', department: 'Information Technology', year_of_study: 4, cgpa: 8.6, coding_score: 83, bio: 'Interested in enterprise application development.', linkedin_url: 'https://linkedin.com/in/shreya-bose', github_url: 'https://github.com/shreyabose', resume_url: null, skills: [3, 27, 21, 8, 39] },
  { email: 'pranav.more@student.com', password: 'demo123', full_name: 'Pranav More', phone: '9876500019', department: 'Computer Science', year_of_study: 3, cgpa: 7.9, coding_score: 71, bio: 'C/C++ developer with interest in systems and security.', linkedin_url: 'https://linkedin.com/in/pranav-more', github_url: 'https://github.com/pranavmore', resume_url: null, skills: [4, 5, 10, 42, 43] },
  { email: 'ishaan.kapoor@student.com', password: 'demo123', full_name: 'Ishaan Kapoor', phone: '9876500020', department: 'Computer Science', year_of_study: 4, cgpa: 8.4, coding_score: 79, bio: 'Final-year student with full-stack and API experience.', linkedin_url: 'https://linkedin.com/in/ishaan-kapoor', github_url: 'https://github.com/ishaankapoor', resume_url: null, skills: [1, 6, 30, 28, 38] },
];

const DEMO_COMPANIES = [
  { email: 'infosys@hire.com', password: 'company123', company_name: 'Infosys', industry: 'IT Services', website: 'https://www.infosys.com', description: 'Enterprise digital services and consulting company.', location: 'Bengaluru', logo_url: null, contact_person: 'Ravi Anand', phone: '9800001111' },
  { email: 'tcs@hire.com', password: 'company123', company_name: 'TCS', industry: 'IT Consulting', website: 'https://www.tcs.com', description: 'Global IT consulting and business solutions provider.', location: 'Mumbai', logo_url: null, contact_person: 'Anjali Mehta', phone: '9800002222' },
  { email: 'wipro@hire.com', password: 'company123', company_name: 'Wipro', industry: 'IT Services', website: 'https://www.wipro.com', description: 'Technology services and consulting organization.', location: 'Hyderabad', logo_url: null, contact_person: 'Sunil Rao', phone: '9800003333' },
  { email: 'google@hire.com', password: 'company123', company_name: 'Google India', industry: 'Technology', website: 'https://about.google', description: 'Search, cloud, ads, and large-scale software products.', location: 'Bengaluru', logo_url: null, contact_person: 'Preethi S', phone: '9800004444' },
  { email: 'amazon@hire.com', password: 'company123', company_name: 'Amazon Development Center', industry: 'E-Commerce / Cloud', website: 'https://www.amazon.jobs', description: 'Builds large-scale e-commerce and AWS systems.', location: 'Hyderabad', logo_url: null, contact_person: 'Deepak Nair', phone: '9800005555' },
  { email: 'flipkart@hire.com', password: 'company123', company_name: 'Flipkart', industry: 'E-Commerce', website: 'https://www.flipkartcareers.com', description: 'Consumer commerce platform focused on India.', location: 'Bengaluru', logo_url: null, contact_person: 'Anand Krishnan', phone: '9800006666' },
  { email: 'zomato@hire.com', password: 'company123', company_name: 'Zomato', industry: 'Food-Tech', website: 'https://www.zomato.com', description: 'Food delivery and restaurant discovery platform.', location: 'Gurugram', logo_url: null, contact_person: 'Nitin Sharma', phone: '9800007777' },
  { email: 'swiggy@hire.com', password: 'company123', company_name: 'Swiggy', industry: 'Food-Tech', website: 'https://careers.swiggy.com', description: 'On-demand delivery and logistics platform.', location: 'Bengaluru', logo_url: null, contact_person: 'Rahul Jain', phone: '9800008888' },
  { email: 'razorpay@hire.com', password: 'company123', company_name: 'Razorpay', industry: 'FinTech', website: 'https://razorpay.com', description: 'Online payments and banking platform for businesses.', location: 'Bengaluru', logo_url: null, contact_person: 'Vivek Kumar', phone: '9800009999' },
  { email: 'byju@hire.com', password: 'company123', company_name: "BYJU'S", industry: 'EdTech', website: 'https://byjus.com', description: 'Digital education and learning products company.', location: 'Bengaluru', logo_url: null, contact_person: 'Sanjana Pillai', phone: '9800000000' },
];

module.exports = {
  ADMIN_CREDENTIAL,
  DEMO_COMPANIES,
  DEMO_STUDENTS,
};
